pageInfo:
  title: Ghosteye
  description: Welcome to my private infra overview!
  navLinks:
    - title: GitHub
      path: https://github.com/markoburcul/nixos-config
appConfig:
  theme: tiger
  layout: auto
  iconSize: large
sections:
  - name: System Monitoring
    displayData:
      sortBy: most-used
      rows: 2
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - &ref_0
        title: Grafana
        description: Grafana instance for personal infra
        icon: hl-grafana
        url: https://grafana.cybercraftsolutions.eu/
        target: newtab
        id: 0_1739_grafana
      - &ref_1
        title: Prometheus
        description: Prometheus instance for personal infra
        icon: hl-prometheus
        url: https://prometheus.cybercraftsolutions.eu/
        target: newtab
        id: 1_1739_prometheus
      - &ref_2
        title: Uptime Kuma
        description: Service for healthchecks
        icon: https://uptime.kuma.pet/img/icon.svg
        url: https://kuma.cybercraftsolutions.eu/
        target: newtab
        id: 2_1739_uptimekuma
    filteredItems:
      - *ref_0
      - *ref_1
      - *ref_2
