{
 "title": "System metrics",
 "description": "Host resources dashboard",
 "tags": [
  "resources",
  "netdata"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(netdata_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Main",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "netdata_system_load_load_average{hostname=\"[[host:pipe]]\"}",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Percent of CPU usage.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "netdata_system_cpu_percentage_average{hostname=~\"[[host]]\"}",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "netdata_system_ram_MiB_average{hostname=\"[[host:pipe]]\"}",
     "legendFormat": "ram.{{dimension}}"
    },
    {
     "expr": "netdata_system_swap_MiB_average{hostname=\"[[host:pipe]]\"}",
     "legendFormat": "swap.{{dimension}}"
    },
    {
     "expr": "netdata_mem_swap_MiB_average{hostname=\"[[host:pipe]]\"}",
     "legendFormat": "swap.{{dimension}}"
    }
   ]
  },
  {
   "title": "Processes Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "netdata_system_processes_processes_average{hostname=\"[[host:pipe]]\"}",
     "legendFormat": "# {{dimension}}"
    }
   ]
  },
  {
   "title": "Software System IRQs",
   "type": "timeseries",
   "description": "CPU softirqs in detail. At the CPUs section, softirqs are analyzed per CPU core.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "netdata_system_softirqs_softirqs_persec_average{hostname=\"[[host:pipe]]\"}",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "System IRQs",
   "type": "timeseries",
   "description": "CPU interrupts in detail. At the CPUs section, interrupts are analyzed per CPU core.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "netdata_system_interrupts_interrupts_persec_average{hostname=\"[[host:pipe]]\"}",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (dimension)(netdata_net_packets_packets_persec_average{hostname=\"[[host:pipe]]\"})",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "netdata_net_net_kilobits_persec_average{hostname=\"[[host:pipe]]\"}",
     "legendFormat": "{{family}}:{{dimension}}"
    }
   ]
  },
  {
   "title": "TCP Socket States",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "netdata_ipv4_sockstat_tcp_sockets_sockets_average{hostname=\"[[host:pipe]]\"}",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "TCP Connections Aborted (1 min)",
   "type": "timeseries",
   "description": "TCP connection aborts. baddata (TCPAbortOnData) happens while the connection is on FIN_WAIT1 and the kernel receives a packet with a sequence number beyond the last one for this connection - the kernel responds with RST (closes the connection). userclosed (TCPAbortOnClose) happens when the kernel receives data on an already closed connection and responds with RST. nomemory (TCPAbortOnMemory happens when there are too many orphaned sockets (not attached to an fd) and the kernel has to drop a connection - sometimes it will send an RST, sometimes it won't. timeout (TCPAbortOnTimeout) happens when a connection times out. linger (TCPAbortOnLinger) happens when the kernel killed a socket that was already closed by the application and lingered around for long enough. failed (TCPAbortFailed) happens when the kernel attempted to send an RST but failed because there was no memory available.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "netdata_ip_tcpconnaborts_connections_persec_average{hostname=\"[[host:pipe]]\"} * 60",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Network Packet Drops",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (family,dimension)(netdata_net_drops_drops_persec_average{hostname=\"[[host:pipe]]\"})",
     "legendFormat": "{{family}}:{{dimension}}"
    }
   ]
  },
  {
   "title": "Network Errors Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (family,dimension)(netdata_net_errors_errors_persec_average{hostname=\"[[host:pipe]]\"})",
     "legendFormat": "{{family}}:{{dimension}}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Await Operation Average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "netdata_disk_await_milliseconds_operation_average{hostname=\"[[host:pipe]]\"}",
     "legendFormat": "{{family}} - {{dimension}}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "netdata_disk_util___of_time_working_average{hostname=\"[[host]]\"}",
     "legendFormat": "{{family}}"
    }
   ]
  },
  {
   "title": "Disk Space Available",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "netdata_disk_space_GiB_average{hostname=\"[[host]]\", family=~\"/|/data|/mnt/.*\", dimension=\"avail\"}",
     "legendFormat": "{{family}}"
    }
   ]
  },
  {
   "title": "Disk Bandwidth Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "netdata_disk_io_KiB_persec_average{hostname=\"[[host]]\"}",
     "legendFormat": "{{family}}"
    }
   ]
  },
  {
   "title": "File Descriptors Open by User",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (user)(netdata_user_fds_open_fds_average{hostname=~\"[[host]]\"})",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Disk Operations Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "netdata_disk_ops_operations_persec_average{hostname=\"[[host]]\"}",
     "legendFormat": "{{family}} - {{dimension}}"
    }
   ]
  },
  {
   "title": "I/O read/write Average",
   "type": "timeseries",
   "description": "Average Input/Output read/write rate in kilobytes per second.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "netdata_disk_io_KiB_persec_average{hostname=~\"[[host]]\"}",
     "legendFormat": "{{chart}}({{dimension}})"
    }
   ]
  },
  {
   "title": "Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Services CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "netdata_services_cpu_percentage_average{hostname=~\"[[host]]\"}",
     "legendFormat": "{{ dimension  }}"
    },
    {
     "expr": "netdata_systemd_service_cpu_utilization_percentage_average{hostname=~\"[[host]]\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Services Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "netdata_services_mem_usage_MiB_average{hostname=\"$host\"}",
     "legendFormat": "{{dimension}}"
    },
    {
     "expr": "netdata_systemd_service_memory_usage_MiB_average{hostname=~\"[[host]]\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Services Throttle I/O Reads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "netdata_services_throttle_io_read_KiB_persec_average{hostname=~\"[[host]]\"}",
     "legendFormat": "{{dimension}}"
    },
    {
     "expr": "netdata_systemd_service_disk_io_KiB_persec_average{hostname=~\"[[host]]\"}",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Services Throttle I/O Writes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "netdata_services_throttle_io_write_KiB_persec_average{hostname=~\"[[host]]\"}",
     "legendFormat": "{{dimension}}"
    },
    {
     "expr": "netdata_systemd_service_disk_io_KiB_persec_average{hostname=~\"[[host]]\"}",
     "legendFormat": "{{dimension}}"
    }
   ]
  }
 ]
}